//
//  PushTokenRegistrar.swift
//  Vibez
//
//  Owns the FCM registration token, the user-entered Vibez ID, and the
//  round-trip to the Vibez Cloud Functions backend. Set as
//  `Messaging.messaging().delegate` in AppDelegate so iOS hands us the
//  token as soon as APN ↔ FCM exchange completes. On every fresh
//  token OR fresh Vibez ID, we POST both to `registerPushToken`,
//  which persists the pairing in the "tokens" Firestore database.
//  The plugin's /notify call on the server queries that pairing to
//  find which device(s) to fan a push out to.
//

import FirebaseFunctions
import FirebaseMessaging
import Foundation
import OSLog

@MainActor
@Observable
final class PushTokenRegistrar: NSObject, MessagingDelegate {

    /// Singleton so AppDelegate can install us as the FCM delegate
    /// before any SwiftUI view exists, and so the setup card can reach
    /// the same instance via `.shared`.
    static let shared = PushTokenRegistrar()

    enum State: Equatable {
        case idle              // No FCM token yet and/or no Vibez ID
        case registering
        case registered
        case error(String)
    }

    /// 4 hyphen-separated lowercase words, each 3-5 letters. Same
    /// pattern the server enforces — generated by the plugin's
    /// setup.sh, typed in by the user.
    static let vibezIdPattern = #"^[a-z]{3,5}(-[a-z]{3,5}){3}$"#

    private(set) var state: State = .idle
    /// Transient cache of the latest FCM registration token, so
    /// `registerIfPossible` doesn't have to re-fetch
    /// `Messaging.messaging().fcmToken` on every call.
    private(set) var lastToken: String?

    /// The Vibez ID the user has entered. Persisted in UserDefaults so
    /// it survives across launches. Setting it triggers a fresh
    /// `registerPushToken` call as soon as we have an FCM token.
    private(set) var vibezId: String = ""

    private let log = Logger(subsystem: "vibezlol.Vibez", category: "PushTokenRegistrar")
    private let functions: Functions
    private let defaults = UserDefaults.standard

    private enum Key {
        static let vibezId = "vibez.vibezId"
    }

    override init() {
        self.functions = Functions.functions()
        super.init()
        // Restore the persisted Vibez ID, if any.
        if let stored = defaults.string(forKey: Key.vibezId) {
            self.vibezId = stored
        }
    }

    // MARK: - Public API

    /// Validate format + persist + (re)register. Returns true if the
    /// ID is well-formed and was stored; false if it's malformed (the
    /// setup card surfaces validation feedback in that case).
    @discardableResult
    func setVibezId(_ raw: String) -> Bool {
        let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        guard Self.isValidVibezId(trimmed) else { return false }
        if trimmed == vibezId {
            // Same value — still kick a re-register in case the prior
            // call failed (e.g. user retried after fixing network).
            Task { await registerIfPossible() }
            return true
        }
        vibezId = trimmed
        defaults.set(trimmed, forKey: Key.vibezId)
        Task { await registerIfPossible() }
        return true
    }

    /// Re-send the current token + ID without waiting for a new FCM
    /// callback. Used by the setup card's retry affordance.
    func reregister() async {
        await registerIfPossible()
    }

    static func isValidVibezId(_ candidate: String) -> Bool {
        candidate.range(of: vibezIdPattern, options: .regularExpression) != nil
    }

    // MARK: - MessagingDelegate

    nonisolated func messaging(
        _ messaging: Messaging,
        didReceiveRegistrationToken fcmToken: String?
    ) {
        Task { @MainActor [weak self] in
            self?.lastToken = fcmToken
            await self?.registerIfPossible()
        }
    }

    // MARK: - Implementation

    /// Single funnel for registration. Skips silently when we don't
    /// have both an FCM token AND a Vibez ID — those are the
    /// preconditions, and the setup card's status surfaces whichever
    /// is missing.
    private func registerIfPossible() async {
        guard let token = lastToken ?? Messaging.messaging().fcmToken,
              !token.isEmpty else {
            // Wait for the next FCM delegate callback.
            return
        }
        lastToken = token
        guard !vibezId.isEmpty else {
            // User hasn't entered their Vibez ID yet. Stay idle so the
            // setup card prompts them.
            state = .idle
            return
        }
        state = .registering
        log.info("Registering push token with Vibez ID")
        let doneSeconds =
            defaults.object(forKey: "vibez.blockSeconds.done") as? Int ?? 30
        let needsSeconds =
            defaults.object(forKey: "vibez.blockSeconds.needsInput")
                as? Int ?? 900
        do {
            _ = try await functions
                .httpsCallable("registerPushToken")
                .call([
                    "fcmToken": token,
                    "vibezId": vibezId,
                    "platform": "ios",
                    "blockSecondsDone": doneSeconds,
                    "blockSecondsNeedsInput": needsSeconds,
                ])
            state = .registered
            log.info("registerPushToken OK")
        } catch {
            // Unpack the Firebase Functions error so the card shows
            // the underlying code (e.g. "permission-denied",
            // "invalid-argument") and any server-supplied details.
            let ns = error as NSError
            var pieces: [String] = []
            pieces.append("\(ns.domain) \(ns.code)")
            pieces.append(ns.localizedDescription)
            if let details = ns.userInfo["details"] {
                pieces.append("details=\(details)")
            }
            if let underlying = ns.userInfo[NSUnderlyingErrorKey] as? NSError {
                pieces.append("underlying=\(underlying.code) \(underlying.localizedDescription)")
            }
            let message = pieces.joined(separator: " | ")
            state = .error(message)
            log.error("registerPushToken failed: \(message, privacy: .public)")
        }
    }
}

#if DEBUG
extension PushTokenRegistrar {
    /// Yields a fresh PushTokenRegistrar pinned to a given vibezId + state.
    /// Used by ContentView previews to render the "paired" home screen
    /// without doing the FCM round-trip. Same-file access lets us write
    /// through the otherwise-private(set) fields.
    static func previewRegistrar(
        vibezId: String = "moss-pine-fox-jazz",
        state: State = .registered
    ) -> PushTokenRegistrar {
        let r = PushTokenRegistrar()
        r.vibezId = vibezId
        r.state = state
        r.lastToken = "preview-fcm-token"
        return r
    }
}
#endif
